import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  dashboard: {
    flex: 1,
    backgroundColor: '#000000',
    overflow: 'hidden',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    borderBottomWidth: 2,
    borderBottomColor: '#00ffff',
    backgroundColor: 'rgba(0, 20, 20, 0.9)',
    // Lift the entire header above the toolbarBar / gridContainer so the
    // absolute-positioned MENU dropdown isn't half-covered by later siblings.
    zIndex: 100,
    // RN-web honours `zIndex`; native uses `elevation` for the same effect.
    elevation: 100,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  title: {
    fontFamily: 'Courier New',
    fontSize: 14,
    fontWeight: 'bold',
    color: '#00ffff',
    letterSpacing: 2,
  },
  spaceTabs: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  spaceTab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#001a1a',
    borderWidth: 1,
    borderColor: '#004444',
    borderRadius: 4,
    gap: 6,
  },
  spaceTabActive: {
    backgroundColor: '#003333',
    borderColor: '#00ffff',
  },
  spaceTabText: {
    fontFamily: 'Courier New',
    fontSize: 11,
    color: '#888888',
  },
  spaceTabTextActive: {
    color: '#00ffff',
  },
  spaceShortcut: {
    fontFamily: 'Courier New',
    fontSize: 9,
    color: '#444444',
  },
  spaceDeleteBtn: {
    marginLeft: 4,
    padding: 2,
  },
  spaceDeleteText: {
    fontFamily: 'Courier New',
    fontSize: 14,
    color: '#666666',
  },
  addSpaceBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#001a1a',
    borderWidth: 1,
    borderColor: '#004444',
    borderRadius: 4,
  },
  addSpaceBtnText: {
    fontFamily: 'Courier New',
    fontSize: 14,
    color: '#00ffff',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  status: {
    fontFamily: 'Courier New',
    fontSize: 10,
  },
  user: {
    fontFamily: 'Courier New',
    fontSize: 10,
    color: '#00cccc',
  },
  settingsMenuBtn: {
    borderWidth: 1,
    borderColor: '#00ffff',
    paddingHorizontal: 12,
    paddingVertical: 4,
    backgroundColor: '#001a1a',
  },
  settingsMenuBtnText: {
    fontFamily: 'Courier New',
    fontSize: 10,
    color: '#00ffff',
    fontWeight: 'bold',
  },
  settingsMenu: {
    position: 'absolute',
    top: '100%',
    right: 0,
    marginTop: 4,
    backgroundColor: '#0a0a0a',
    borderWidth: 1,
    borderColor: '#00ffff',
    borderRadius: 4,
    minWidth: 200,
    zIndex: 9999,
    elevation: 9999,
  },
  settingsMenuItem: {
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  settingsMenuItemText: {
    fontFamily: 'Courier New',
    fontSize: 11,
    color: '#00ffff',
  },
  settingsMenuDivider: {
    height: 1,
    backgroundColor: '#004444',
    marginHorizontal: 8,
  },
  gridContainer: {
    flex: 1,
  },
  gridContainerSystem: {
    borderTopWidth: 1,
    borderTopColor: '#00ffff',
  },
  systemBanner: {
    borderWidth: 1,
    borderColor: '#006666',
    backgroundColor: 'rgba(0,255,255,0.05)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginBottom: 8,
  },
  systemBannerText: {
    fontFamily: 'Courier New',
    fontSize: 10,
    color: '#00cccc',
    letterSpacing: 1,
  },
  gridSettings: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  gridSettingsLabel: {
    fontFamily: 'Courier New',
    fontSize: 10,
    color: '#00ffff',
  },
  gridSizeSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  gridSizeBtn: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: '#001a1a',
    borderWidth: 1,
    borderColor: '#004444',
    borderRadius: 2,
  },
  gridSizeBtnActive: {
    backgroundColor: '#00ffff',
    borderColor: '#00ffff',
  },
  gridSizeBtnText: {
    fontFamily: 'Courier New',
    fontSize: 10,
    color: '#00ffff',
  },
  gridSizeBtnTextActive: {
    color: '#000000',
  },
  gridSettingsX: {
    fontFamily: 'Courier New',
    fontSize: 10,
    color: '#666666',
    marginHorizontal: 4,
  },
  gridSettingsHint: {
    fontFamily: 'Courier New',
    fontSize: 10,
    color: '#444444',
    marginLeft: 16,
  },
  spaceSettingsBtn: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    backgroundColor: '#001a1a',
    borderWidth: 1,
    borderColor: '#00ffff',
    borderRadius: 2,
  },
  spaceSettingsBtnText: {
    fontFamily: 'Courier New',
    fontSize: 10,
    color: '#00ffff',
  },
  datePickerLabel: {
    fontFamily: 'Courier New',
    fontSize: 10,
    color: '#00ffff',
  },
  toolbarBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  datePickerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  dateQuickBtn: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: '#001a1a',
    borderWidth: 1,
    borderColor: '#004444',
    borderRadius: 2,
  },
  dateQuickBtnActive: {
    backgroundColor: '#00ffff',
    borderColor: '#00ffff',
  },
  dateQuickBtnText: {
    fontFamily: 'Courier New',
    fontSize: 10,
    color: '#00ffff',
    fontWeight: 'bold',
  },
  dateQuickBtnTextActive: {
    color: '#000000',
  },
  datePickerSeparator: {
    width: 1,
    height: 20,
    backgroundColor: '#004444',
    marginHorizontal: 4,
  },
  dateNavBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: '#001a1a',
    borderWidth: 1,
    borderColor: '#004444',
    borderRadius: 2,
  },
  dateNavBtnText: {
    fontFamily: 'Courier New',
    fontSize: 10,
    color: '#00ffff',
  },
  datePickerDisplay: {
    fontFamily: 'Courier New',
    fontSize: 11,
    color: '#00cccc',
    marginLeft: 8,
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  settingsModal: {
    backgroundColor: '#0a0a0a',
    borderWidth: 2,
    borderColor: '#00ffff',
    borderRadius: 4,
    minWidth: 320,
    maxWidth: 400,
  },
  settingsModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#004444',
  },
  settingsModalTitle: {
    fontFamily: 'Courier New',
    fontSize: 12,
    fontWeight: 'bold',
    color: '#00ffff',
    letterSpacing: 1,
  },
  settingsModalClose: {
    fontFamily: 'Courier New',
    fontSize: 20,
    color: '#666666',
  },
  settingsModalContent: {
    padding: 16,
  },
  settingsSection: {
    marginBottom: 16,
  },
  settingsSectionLabel: {
    fontFamily: 'Courier New',
    fontSize: 10,
    color: '#00ffff',
    marginBottom: 12,
    letterSpacing: 1,
  },
  gridSizeLabel: {
    fontFamily: 'Courier New',
    fontSize: 10,
    color: '#888888',
    marginRight: 8,
    width: 60,
  },
  settingsOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#002222',
  },
  settingsOptionLabel: {
    fontFamily: 'Courier New',
    fontSize: 11,
    color: '#cccccc',
  },
  settingsToggle: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    backgroundColor: '#1a0000',
    borderWidth: 1,
    borderColor: '#660000',
    borderRadius: 2,
  },
  settingsToggleActive: {
    backgroundColor: '#001a00',
    borderColor: '#00ff00',
  },
  settingsToggleText: {
    fontFamily: 'Courier New',
    fontSize: 10,
    color: '#00ff00',
    fontWeight: 'bold',
  },
  settingsToggleTextOff: {
    color: '#ff6666',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#004444',
    backgroundColor: 'rgba(0, 20, 20, 0.8)',
  },
  footerText: {
    fontFamily: 'Courier New',
    fontSize: 10,
    color: '#666666',
  },
});
